#!/bin/bash

set -e

cd "$(dirname "$0")"

CLI_NAME="shawky"
INSTALL_PATH="/usr/local/bin/.shawkyCLI"
BIN_PATH="/usr/local/bin/$CLI_NAME"
DOWNLOAD_URL="https://github.com/AhmedShawkyAhmed/shawky_cli/releases/latest/download/shawkyCLI.zip"
ZIP_PASSWORD="6db276063e7b9881b63f9876fe787dd36e835249bd26b361e1cf50d4bbdc5fc1"

echo "🔧 Installing $CLI_NAME CLI..."

# Remove any existing install
sudo rm -rf "$INSTALL_PATH"
sudo rm -f "$BIN_PATH"

# Create new install directory
sudo mkdir -p "$INSTALL_PATH"

echo "📥 Downloading shawkyCLI..."
curl -L "$DOWNLOAD_URL" -o "shawkyCLI.zip"

if [ ! -f "shawkyCLI.zip" ]; then
    echo "❌ Download failed! Please check the URL."
    exit 1
fi

echo "📦 Unzipping the downloaded file with password..."
sudo unzip -P "$ZIP_PASSWORD" -q "shawkyCLI.zip" -d "$INSTALL_PATH"

rm "shawkyCLI.zip"

echo "🔗 Creating symlink for the CLI script..."
sudo ln -s "$INSTALL_PATH/$CLI_NAME" "$BIN_PATH"
sudo chmod +x "$BIN_PATH"

echo "✅ Installed! You can now run the CLI by typing: $CLI_NAME"

sleep 1
exit 0
