name: Delete Assets from Release

on:
  release:
    types:
      - published  # Trigger when a new release is published
  workflow_dispatch:  # Allow manual trigger

jobs:
  delete-assets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List release assets
        env:
          GH_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
        run: |
          release_tag="${{ github.event.release.tag_name }}"
          echo "Listing assets for release: $release_tag"
          gh release view "$release_tag" --json assets -q ".assets[].name"

      - name: Delete source code assets
        env:
          GH_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
        run: |
          release_tag="${{ github.event.release.tag_name }}"
          release_exists=$(gh release view "$release_tag" --json id -q ".id" || echo "not found")

          if [ "$release_exists" != "not found" ]; then
            # List all assets and filter based on zip file or source code name
            asset_ids=$(gh release view "$release_tag" --json assets -q ".assets[] | select(.name | contains(\"source code\") or contains(\".zip\")) | .id")

            for asset_id in $asset_ids; do
              echo "Deleting asset: $asset_id"
              gh release delete $asset_id --repo AhmedShawkyAhmed/shawky_cli -y
            done
          else
            echo "Release $release_tag not found, skipping asset deletion."
          fi
